### ISSUE TITLE
Remove unnecessary? Picasa files from img directory in code

### ISSUE THREAD

**Issue by timwood** [CommerceGov/DataCorps_WebSite#10]
https://github.com/CommerceGov/DataCorps_WebSite/tree/gh-pages/img contains a .picasa.ini, .picasaoriginals and lots of gifs that are not needed on the website. Remove all images that aren't used on the site.

**Comment by SigmaMonstR** [comment]
Already removed on an uncommitted commit

Jeff Chen 
jeffchen.org
contact@jeffchen.org
914-837-1336

On Sep 11, 2015, at 14:58, Tim Wood <notifications@github.com> wrote:

https://github.com/CommerceGov/DataCorps_WebSite/tree/gh-pages/img contains a .picasa.ini, .picasaoriginals and lots of gifs that are not needed on the website. Remove all images that aren't used on the site.

**Comment by timwood** [comment]
@SigmaMonstR Please push this commit so I can update on server and remove these files.

**Comment by timwood** [comment]
There is still one .picasa.ini file in the /img folder. You could also use a .gitignore to make sure files like these don't end up in the repo in the future.

**Comment by SigmaMonstR** [comment]
Noted. Will amend in next commit.

On Wed, Sep 16, 2015 at 10:07 AM, Tim Wood <notifications@github.com> wrote:

> There is still one .picasa.ini file in the /img folder. You could also use
> a .gitignore to make sure files like these don't end up in the repo in the
> future.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CommerceGov/DataCorps_WebSite/issues/10#issuecomment-140752220>
> .
>



-- 
*Jeff Chen *
jeffchen.org
contact@jeffchen.org
914-837-1336

**Comment by SigmaMonstR** [comment]
​Ready to go. Please update on server.

On Wed, Sep 16, 2015 at 10:11 AM, Jeff Chen <jchen85@gmail.com> wrote:

> Noted. Will amend in next commit.
>
> On Wed, Sep 16, 2015 at 10:07 AM, Tim Wood <notifications@github.com>
> wrote:
>
>> There is still one .picasa.ini file in the /img folder. You could also
>> use a .gitignore to make sure files like these don't end up in the repo in
>> the future.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/CommerceGov/DataCorps_WebSite/issues/10#issuecomment-140752220>
>> .
>>
>
>
>
> --
> *Jeff Chen *
> jeffchen.org
> contact@jeffchen.org
> 914-837-1336
>
>


-- 
*Jeff Chen *
jeffchen.org
contact@jeffchen.org
914-837-1336
