### ISSUE TITLE
Hamburger mobile menu isn't scrollable and the active item is the Commerce Leadership page

### ISSUE THREAD

**Issue by timwood** [CommerceGov/DataCorps_WebSite#11]
* [x] Cannot scroll the mobile menu making it impossible to get to items at the lower portion of the menu, especially when a part of the menu is expanded.
* [x] Active item should be nothing for now. Remove "active" class from Commerce Leadership link in mobile menu.

**Comment by SigmaMonstR** [comment]
Removed scrolling restrictions
