### ISSUE TITLE
Map background image no longer centered and repeats

### ISSUE THREAD

**Issue by timwood** [CommerceGov/DataCorps_WebSite#15]
![background map repeating](https://cloud.githubusercontent.com/assets/91050/9941914/48de9f40-5d46-11e5-90aa-006bc049953e.PNG)

![background map not centered](https://cloud.githubusercontent.com/assets/91050/9941913/48db53e4-5d46-11e5-8107-c938c265ba67.PNG)

**Comment by tyronegrandison** [comment]
@timwood Is this still an issue?

**Comment by timwood** [comment]
Looks like it's fixed.
