### ISSUE TITLE
Spacing, text, font and icon issues in footer

### ISSUE THREAD

**Issue by timwood** [CommerceGov/DataCorps_WebSite#2]
* [ ] Spacing between main menu items and sub-items isn't quite right. (see screenshots below)
* [x] Icon quality is visibally lower and is implemented in code differently than on C.gov (see screenshots below) (this one seems to apply to the heading too)
* [x] Font family, color and size seems to be different than on C.gov.

<img width="336" alt="screen shot 2015-09-11 at 9 22 57 am" src="https://cloud.githubusercontent.com/assets/91050/9815898/74222e12-5867-11e5-8363-45e561f1ca65.png">

VS.

<img width="280" alt="screen shot 2015-09-11 at 9 28 34 am" src="https://cloud.githubusercontent.com/assets/91050/9815910/838034bc-5867-11e5-98de-c00aff69b60e.png">

**Comment by SigmaMonstR** [comment]
- Regarding resolution and font, I have a feeling this might be a dependencies issue based on the results of testing a ripped Commerce page on a local server. Can we put the code on a test server to see if some issues would be fixed by way of access to certain dependencies?
- Figured out why the Bureaus & Offices block was shifted down. Simple <section> padding issue.
- Just in case, is the font used "SourceSansProRegular"?  I'll patch up the bootstrap code to avoid any CSS conflicts. Between list item spacing is also a bootstrap issue.

**Comment by timwood** [comment]
We can put a copy of the site directly onto Commerce.gov under either an unpublished, temporary path or under a path restricted by IP address.

**Comment by alisonjo2786** [comment]
"Regarding resolution and font, I have a feeling this might be a dependencies issue based on the results of testing a ripped Commerce page on a local server."
>> I think the font family is getting overridden by creative.css, based on what I'm seeing in the inspector.

**Comment by alisonjo2786** [comment]
>Just in case, is the font used "SourceSansProRegular"?

Yes, our declared font-family is: "SourceSansProRegular","Helvetica Neue",Arial,Helvetica,sans-serif

**Comment by SigmaMonstR** [comment]
I've amended it across all css files on my side

**Comment by timwood** [comment]
Did all three concerns get address? Doesn't seem like it has, at least not on the copy in AWS. I suggest leaving this open until we can put up a copy on C.gov. Let me know when you'd like me to do a git clone from this repo to the server and which option from my previous https://github.com/CommerceGov/DataCorps_WebSite/issues/2#issuecomment-139576744 that you want to use.

**Comment by tyronegrandison** [comment]
@timwood thanks. can you clone it to an unpublished, temporary path on Commerce.gov ?

**Comment by timwood** [comment]
@tyronegrandison and @SigmaMonstR I've cloned the site to the web server and I've emailed the url directly.

**Comment by alisonjo2786** [comment]
Things look better -- especially font family and color -- but still some issues.  One that stuck out to me is the "p, pre" style rule in creative.css (line 42) -- seems to be affecting font size and spacing.  Idk if there are other rules interfering with the styling consistency, this one was just what jumped out at me.

**Comment by SigmaMonstR** [comment]
items 2 and 3 are taken care of.

**Comment by SigmaMonstR** [comment]
item 1 - adjusted in the bootstrap.css (margin issue)
items 2 and 3 - addressed by putting on c.gov server.
closing out.

**Comment by alisonjo2786** [comment]
@SigmaMonstR The spacing between main menu items and sub-menu items is still off (that is, the vertical space between "LEARN ABOUT COMMERCE" and "About Commerce," and the vertical space between "FIND DATA" and "Digital Strategy," etc.), and also the vertical space between the last sub-menu item and the next main menu item (that is, the space between "Contact Us" and "BROWSE BY TOPIC").  (Refer to original screenshots from @timwood for illustration of these differences.)
