### ISSUE TITLE
Landing page speed

### ISSUE THREAD

**Issue by alisonjo2786** [CommerceGov/DataCorps_WebSite#3]
When I go to the homepage for the first time (or with ctrl+F5), the images and other assets load verrrrrrry slowly, and it looks icky during that load time (see screenshots).

![datacorps_homepage-slowness1](https://cloud.githubusercontent.com/assets/2660348/9818259/9f73ccac-5875-11e5-8e4d-5b028f7577aa.png)
![datacorps_homepage-slowness2](https://cloud.githubusercontent.com/assets/2660348/9818260/9f78a1c8-5875-11e5-9c53-69f3d1a20dcd.png)

**Comment by SigmaMonstR** [comment]
I re-jiggered the script loads, then tried it on a 2014 Macbook Pro (really fast) and a 2009 ThinkPad (really slow) to see differences in the download speeds and the bouncing. It seems to have minimal bouncing now. Can you give it another shot?

**Comment by alisonjo2786** [comment]
How it looks during loading is improved -- it's definitely less ugly :)  But the page still takes > 9 seconds to load for me.

(It wasn't terribly bouncy for me, it's just that the fonts are off, and bold text is invisible at first, and the fonticons in the navbar don't load (you see those "broken character" rectangles in my second screenshot) -- maybe some JS is changing the font on pageload, or maybe different stylesheets are loading sooner/later?)

Just from an eye test, the slowest thing to load is the map image -- it fills itself in for several seconds.

**Comment by tyronegrandison** [comment]
I am on a MacBook and these are speeds I get:

Safari 2secs
Chrome 3secs
Firefox 3 secs
Aviator 3 secs

**Comment by alisonjo2786** [comment]
Maybe it's our network I guess?  I'll try on my other computer, tho it's an ancient Lenovo running Ubuntu so that probably isn't the best test :)  But we'll see :)

**Comment by alisonjo2786** [comment]
I'm getting 5 seconds in FF on my little old lenovo.

Meanwhile, it's taking even longer on my (shiny new, albeit government-issued) Dell -- 10 secs til the map image is shown, almost 15 secs til the page finishes loading :(

BUT... the image isn't loading gradually anymore -- it's just not there at all and then all there at once, which is probably better than before?

But overall, still very slow :(  I'll disconnect from VPN and try again.

**Comment by alisonjo2786** [comment]
Holy crap -- down to under 3 secs, just like that.  Wow.

So I that explains that.  Whether or not to care about the in-network speed I think is up to you, but probably should run it by @MikeKruger -- he usually has to care about UX of Commerce people because those are the people who are most likely to complain and cause trouble for him, but in the case of this site it might be the DataCorps team's call, I'm not sure.

Might also be worth asking a few people at other government agencies to look from within their work networks -- again, if you decide to care about it, not a big deal to me either way.

**Comment by tyronegrandison** [comment]
Interesting. What is your take @MikeKruger ?

**Comment by tyronegrandison** [comment]
Thinking about it, intranet speed is nothing we have control over. So, closing this issue.

**Comment by timwood** [comment]
I agree with reason for closing. Also, VPN is generally going to be slower since the requests have to go across VPN. If someone is on DOC network w/out VPN, maybe they can provide input about speed. OR was that where you tested from @tyronegrandison @SigmaMonstR

**Comment by tyronegrandison** [comment]
I tested on DOC-Guest, HCHB-GuestNet and my home network and averaged 3 secs.
