### ISSUE TITLE
Reference or download bureau logos from official sources

### ISSUE THREAD

**Issue by timwood** [CommerceGov/DataCorps_WebSite#4]
Some of the bureau logos at the bottom are sourced from non-government websites. Even though duplicating content from other government websites is typically not recommended, in this case I would recommend retrieving, storing and referencing the bureau logos in the source code of the DataCorps site. This will ensure if the logo location is changed on the bureau website, the logo still works and also guarantee the images are loaded over HTTPS.

<img width="787" alt="screen shot 2015-09-11 at 10 54 32 am" src="https://cloud.githubusercontent.com/assets/91050/9818782/3a9cd384-5878-11e5-94be-52d9b669b91a.png">

**Comment by timwood** [comment]
@MikeKruger Can you help with sourcing Commerce bureau logos from official locations?

**Comment by alisonjo2786** [comment]
@timwood Or maybe we add the logos to commerce.gov?  Wouldn't be the worst idea to have bureau logos on c.gov, right?

**Comment by timwood** [comment]
@alisonjo2786 That's a good idea. We could add to theme via our git repo or Mike could upload and manage in Drupal.

**Comment by SigmaMonstR** [comment]
Sounds good to me. Happy to replace the src in the imgs.

**Comment by tyronegrandison** [comment]
Who has the lead on this?

**Comment by timwood** [comment]
I was hoping @MikeKruger would respond with help obtaining the logos.

**Comment by MikeKruger** [comment]
Commerce.gov has the most up-to-date and approved logos in our OPA shared folder. However, if you use the logos from the individual pages (listed in right hand side here https://www.commerce.gov/department-commerce), that would be better.

**Comment by timwood** [comment]
Turns out all the current bureau logos are on Commerce.gov. You can see each one on the bureau page in the top right. Mike's link above has links to each bureau page under the "WITHIN DEPARTMENT OF COMMERCE" heading on the top right. You should be able to right click on each image on each bureau page and copy the url ([USPTO for example](https://www.commerce.gov/sites/commerce.gov/files/styles/scale_200x200/public/media/images/branding/uspto_seal_full_color.jpg)) to use directly in your code. If the 200x200 scaled image is too big you can use the 100x100 scaled image style. To use that style replace scale_200x200 with scale_100x100 in the url.

**Comment by SigmaMonstR** [comment]
Updated to reflect logos. Closing now.
