### ISSUE TITLE
"Hamburger mobile menu" missing and responsive issues with top background graphic/text

### ISSUE THREAD

**Issue by timwood** [CommerceGov/DataCorps_WebSite#6]
* [x] When resizing browser to mobile size, the main menu doesn't change into the hamburger menu as seen on C.gov.
* [x] The map and intro text overlay nicely on desktop but on mobile breakpoints the text and "apply to serve" button appear below the image instead of overlayed.
* [x] The grid of bureau logos doesn't reflow properly at mobile breakpoints. Try setting a max-width value (eg. 500px) on the parent div and removing the <br> in the middle of the logos.

<img width="570" alt="screen shot 2015-09-11 at 11 32 57 am" src="https://cloud.githubusercontent.com/assets/91050/9819074/e1728068-5879-11e5-899d-ba2854033ed6.png">

<img width="415" alt="screen shot 2015-09-11 at 11 33 58 am" src="https://cloud.githubusercontent.com/assets/91050/9819079/e497558e-5879-11e5-854f-8a87a7b9b25c.png">

**Comment by SigmaMonstR** [comment]
@timwood Try now

**Comment by timwood** [comment]
@SigmaMonstR I see the menu now and it opens properly (tested via Chrome on Mac and Android) but it doesn't have independent scrolling. When you try to scroll the menu to get to the lower items, it scrolls the page behind the menu.

**Comment by timwood** [comment]
Opening a separate issue for the hamburger scrolling problem.
