### ISSUE TITLE
Engage fonticons

### ISSUE THREAD

**Issue by alisonjo2786** [CommerceGov/DataCorps_WebSite#7]
Engage drop-down panel is missing its fonticons:
![datacorps_navbar-issues2](https://cloud.githubusercontent.com/assets/2660348/9819843/54a5bf1a-587e-11e5-8b8f-abe6a26729d8.png)

**Comment by timwood** [comment]
So is the search one.

**Comment by SigmaMonstR** [comment]
Can we put the project on a test directory? Fonticons don't show up if I download a complete page from c.gov

**Comment by alisonjo2786** [comment]
(I don't have an answer about the test directory, that's a Tim thing, but--)

The Fonticons are there for other things on the page (i.e. the Search / Engage / Share top-level items), just not in these drop-down panels, so I don't know if moving to a Commerce server will help -- but I can understand wanting to try that before fighting with the code too much more.

These drop-down panels can be tricky -- they're hidden (I think visibility:hidden and display:none) on page-load, so certain scripts don't target them properly without extra fiddling sometimes.

**Comment by timwood** [comment]
Also, the search & engage drop downs don't close when clicked a second time.

**Comment by alisonjo2786** [comment]
So that's interesting -- they close when clicked a second time for me, but I noticed that if I went into Firebug/inspector and then tried to close them by clicking again (even if I closed Firebug), they wouldn't close.  Any chance that's what's happening for you?

**Comment by timwood** [comment]
Clicking to close seems to be working now, with or without inspector open.

**Comment by tyronegrandison** [comment]
Let us know if this problem persists on the test server.

**Comment by alisonjo2786** [comment]
Engage fonticons are showing now on the c.gov server (I didn't check before the last pull, so idk if they were already fixed).
