### ISSUE TITLE
508

### ISSUE THREAD

**Issue by delegatrix** [CommerceGov/DataCorps_WebSite#9]
Alt, Label or Title on Input element; and Label on Select element

**Comment by tyronegrandison** [comment]
Please provide more detail in your issue desscription

**Comment by delegatrix** [comment]
To meet 508 compliance (accessibility) The input element needs alt text and the select item needs a label.

**Comment by tyronegrandison** [comment]
Did a quick check. Will update in a minute. 

FYI All the commerce.gov pages need to be updated to meet 508 compliance (using the same rules outlined above)

**Comment by daddymacnrei** [comment]
FYI.  Results from the accessibility testing that Brenda Jenkins (DOC Web Solutions team member) ran for your test site has been sent to your group email, DataCorps@doc.gov, for your review.

**Comment by tyronegrandison** [comment]
Thank you. 

Issue with input and select resolved. 

Closing issue.

**Comment by alisonjo2786** [comment]
Hi Tyrone, I was looking at https://www.commerce.gov/datacorpsbeta/ and thinking that the text over the map images is a little muddled for me to read (especially the lines of smaller text), as someone who doesn't need reading glasses or have any other vision-impairedness (if that were a word). Is there something you can do to improve the contrast of the text compared to the background?  (Also keep in mind color-blind users.)  Like maybe make the transparent text background more opaque, and/or fade the map image, or something like that?

@timwood @MikeKruger @sutch @daddymacnrei what do you think?

**Comment by alisonjo2786** [comment]
Also, I think the bold text blurs together.

**Comment by SigmaMonstR** [comment]
I tried making the background more opaque, but it's harder to read. I upsized the sub-text over the map by 20%. The alternative would be to make the black highlight around the text a full solid as opposed to opacity 0.8.

**Comment by alisonjo2786** [comment]
Sorry I didn't reply on this -- thank you for trying some different things with the text. I think it would help for a little more input on whether others think it's difficult to read or if it's just me.

Same goes for bold text generally on the page.  I'll post a separate comment re-asking for input since they seem to have missed it last time.

**Comment by alisonjo2786** [comment]
@daddymacnrei @timwood @sutch @MikeKruger:

I had a couple of concerns about visual readability:
* I think that bold text everywhere on the page is blurry/gets smushed (smooshed?) together.
* This comment about the white text overlaid on the blue map image: https://github.com/CommerceGov/DataCorps_WebSite/issues/9#issuecomment-140156948

Do you agree with either or both comments, or is it just me?  Thanks!

**Comment by alisonjo2786** [comment]
@SigmaMonstR I figured out the bold thing -- the CSS in our theme applies the font, "SourceSansProBold" and font-weight:normal to <b> and <strong> elements, and then bootstrap.css (line 56) applies font-weight:bold to these elements, thus creating uber-bold, uber-hardtoread text :)

**Comment by tyronegrandison** [comment]
Fixed and closing
